### ISSUE TITLE
undead specific comment in undead only route

### ISSUE THREAD

**Issue by btkramer9** [wickstjo/vanilla-questing#13]
~line 620 of undead.json
`
            {
               "coords": { "x": 62, "y": 65 },
               "align": "bottom",
               "header": "undercity gates",
               "special": ["undeads go straight to silverpine"],
               "type": "travel"
            }
`
The only class that would be following this guide at this point is undead. Why would there be a note for undead to take one path but others (troll, orc, tauren) to take another?

**Comment by wickstjo** [comment]
Very few quests are completely locked behind a specific race, and you accumulate a hefty amount of reputation by doing another factions starting zones. At one point I had plans to add various hints for people doing another factions starters, but it ended up being more confusing so I scrapped it. People who do this likely know the extra steps they need to take anyway.

Undead don't have to learn the flightpath in Undercity, and the route file now reflects that properly. Thank you!

**Comment by btkramer9** [comment]
No problem! The app looks great. Can't wait to use it for launch next week. Cheers.
