### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by ninthwalker** [wickstjo/vanilla-questing#14]
First, thanks for this open source app! Nice job.
I wanted to run it locally, so made a quick simple Dockerfile and pushed it to docker hub.
If you have your own docker hub, here is the [Dockerfile](https://github.com/ninthwalker/vanilla-questing/blob/master/Dockerfile) I made that you could add to your own repo for people to use. Or I can do a pull request from my fork and you can link your repo  to docker hub.

Here is the info for anyone else that wants to run it in docker for the one i made:

`docker run -p 3000:3000 -d ninthwalker/vanilla-questing`

**Comment by wickstjo** [comment]
Docker and open source go hand in hand! I've certainly been looking for excuses to get more into docker but simply been too swamped with this project and work to start learning something new.

I added the command to the readme with credits. Thank you!
