### ISSUE TITLE
How does this compare to Vanilla Guide?

### ISSUE THREAD

**Issue by Vondelphia** [wickstjo/vanilla-questing#15]
Is this a port from the Vanilla Guide questing addon? I also know you've Zygor and Joanna and so many other's and i was reading over your manifesto... just wondering HOW FAST this leveling guide is.... like, the one quest, Demon Seed... is it even worth doing? The 30 minute is brutal right? The DEN? that too.. no way right?

BTW, beautiful work, excellent all around and SUPER NICE. You've done great things. KEEP IT UP!!

**Comment by wickstjo** [comment]
Speed is completely subjective and largely depends on the person sitting behind the screen. Routing isn't rocket science and most properly planned routes take +-5 days of played time. Depending on what class and spec you're playing, this time can drastically vary.

I clear quite thoroughly so you can make the choice whether something is worth doing or not. Compare your current level with the experience estimate and make the call!
