### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by paOol** [wickstjo/vanilla-questing#3]
```
4. The Crossroads	52.31
Consumed By Hatred
Betrayal From Within	P2
Egg Hunt
Set Hearthstone
Fly To Ratchet
```

When hovering over quests in a section ( `4` in this case), 
the `4` on the map should glow , or be highlighted in some manner.

**Comment by wickstjo** [comment]
This was a feature in an easy version of the app, but I ended up scrapping it relatively early after the new codebase since the implementation looked technical and I wasn't very good at React yet.

I'll look into adding it back!

**Comment by wickstjo** [comment]
The old waypoint highlighting system is now live.
