### ISSUE TITLE
Feature request: Link to manifesto in README.md

### ISSUE THREAD

**Issue by ollema** [wickstjo/vanilla-questing#5]
Hi!

This looks awesome. It would be nice if there was a `README.md` here on GitHub!

Since you already have a nice page over at https://www.vanilla-questing.me/manifesto this could included in the `README.md` and it could be held very short.

Let me know if you would like this and I could submit a PR.

Thanks!

**Comment by wickstjo** [comment]
Forgot to respond with a thanks after I added the first draft of the more technical readme. It's easy to keep saying "tomorrow.." until someone asks for it!
