### ISSUE TITLE
Question: Adding a new Quest results in an "undefined" link.

### ISSUE THREAD

**Issue by ixidion** [wickstjo/vanilla-questing#7]
I have added a new Quest to the quests.json in "dev"-Folder, but it is not rendered with the correct link: https://classicdb.ch/?quest=undefined

Is there anything else to do or run?

quests.json
`"WANTED: Chok'sul": 256,`

route.json
```
            {
               "coords": { "x": 35, "y": 47 },
               "align": "right",
               "header": "Thelsamar",
               "starts": ["WANTED: Chok'sul", "Mercenaries"],
               "type": "hub"
            },
```

**Comment by ixidion** [comment]
After Debugging: The questnames in `quests.json` need to be all lower case. A hint in the Readme would be nice.

**Comment by wickstjo** [comment]
Good call. Quests and items have tendency to have "punny" names which means that capitalization and  general spelling can be wonky. Everything in the route files should work properly if you stick to lowercase. If a quest shows up as undefined, it's either misspelled or doesn't exist in the respective ID files.

Publishing the new version of the app takes priority for now, but I'll look into improving the readme afterwards!
