### ISSUE TITLE
Link Feature and Devmode Broken

### ISSUE THREAD

**Issue by ixidion** [wickstjo/vanilla-questing#8]
The Link Feature is broken after commit f5756699f8c76707c40e5fafc84c09c30708cedf

A random page is shown instead of the requested.
The Devmode always shows the first page of devmode and not the last viewed page.

**Comment by wickstjo** [comment]
There a multitude of changes in the code that I've been working on over time. I'll try to get everything up to date this weekend.

[This version](https://github.com/wickstjo/vanilla-questing/tree/b3f9d819ea9e5a509e5dba864f5c0b6bc940b8f7) should be stable.
