### ISSUE TITLE
Layout is broken

### ISSUE THREAD

**Issue by qiazee** [wickstjo/vanilla-questing#9]
On Chromium 76.0.3809.87, the layout of the website is completely broken. Rather than a long speech, I recorded a gif to show the issue (which was not present some days ago).

I tried to clear the cache and all, but it doesn't change anything.

Screen record: https://qiazee.com/vanilla-questing.gif

**Comment by wickstjo** [comment]
Weird, looking into it now.

**Comment by wickstjo** [comment]
The issue should now be fixed after you reload the page. Chromium seems to process percentage values differently than Chrome and Firefox which I wasn't aware of at all. Sorry!

Let me know some issue still persists.

**Comment by qiazee** [comment]
Don't be sorry, your project is awesome, thanks for that! I'm not at home so I can't test your change for now but I'll let you know in the coming days! 🙂

**Comment by qiazee** [comment]
After testing, everything seems to be working! Thank you! I'm closing the issue.
